name: PR Test

on: [ pull_request ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x, 1.20.x ]
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go get ./...

      - name: Run tests
        run: go test ./...
